[package]
name = "nostd_spin_channel"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
spin.workspace = true
thiserror.workspace = true

[lints]
workspace = true
